[build-system]
requires = ["setuptools>=80.9.0"]
build-backend = "setuptools.build_meta"

[project]
name = "supercell_finder"
version = "0.0.0"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pymatgen",
]


[tool.setuptools]
packages = ["supercell_finder"]
